"""Initial schema: all models with UUIDs

Revision ID: c00bfe0a09e5
Revises:
Create Date: 2026-07-07 12:06:52.852227

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "c00bfe0a09e5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
