"""Add Task and Comment models

Revision ID: c38e935010fc
Revises: 2563d1ca4a76
Create Date: 2026-07-24 10:45:00.206208

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c38e935010fc"
down_revision: Union[str, Sequence[str], None] = "2563d1ca4a76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_comments_task_id", "comments", ["task_id"], unique=False)
    op.add_column(
        "tasks", sa.Column("deadline", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("tasks", sa.Column("creator_id", sa.UUID(), nullable=False))
    op.add_column(
        "tasks",
        sa.Column(
            "tags", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
    )
    op.alter_column(
        "tasks",
        "title",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=200),
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "status",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "priority",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tasks",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index("idx_tasks_assignee_id", "tasks", ["assignee_id"], unique=False)
    op.create_index(
        "idx_tasks_deadline",
        "tasks",
        ["deadline"],
        unique=False,
        postgresql_where=sa.text("deadline IS NOT NULL"),
    )
    op.create_index(
        "idx_tasks_status_workspace", "tasks", ["status", "workspace_id"], unique=False
    )
    op.create_index("idx_tasks_workspace_id", "tasks", ["workspace_id"], unique=False)
    op.drop_constraint(op.f("tasks_author_id_fkey"), "tasks", type_="foreignkey")
    op.create_foreign_key(
        None, "tasks", "users", ["creator_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("tasks", "author_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("author_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("tasks_author_id_fkey"),
        "tasks",
        "users",
        ["author_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index("idx_tasks_workspace_id", table_name="tasks")
    op.drop_index("idx_tasks_status_workspace", table_name="tasks")
    op.drop_index(
        "idx_tasks_deadline",
        table_name="tasks",
        postgresql_where=sa.text("deadline IS NOT NULL"),
    )
    op.drop_index("idx_tasks_assignee_id", table_name="tasks")
    op.alter_column(
        "tasks",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tasks",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tasks",
        "priority",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "status",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "title",
        existing_type=sa.String(length=200),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.drop_column("tasks", "tags")
    op.drop_column("tasks", "creator_id")
    op.drop_column("tasks", "deadline")
    op.drop_index("idx_comments_task_id", table_name="comments")
    op.drop_table("comments")
    # ### end Alembic commands ###
