"""init fresh db

Revision ID: e41a3d4cec54
Revises:
Create Date: 2026-07-21 11:22:56.478608

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e41a3d4cec54"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
